module.exports  = {
    STATUS_OK: "OK",
    STATUS_NOK: "NOK",
    
    MENSAJE_NO_AUTENTIFICADO: "NO ESTÁS AUTENTIFICADO",
    MENSAJE_SIN_REGISTRO: "NO SE ENCONTRO REGISTROS",
    MENSAJE_CORRECTO: "EJECUCION CORRECTA",
    MENSAJE_ERROR: "UPS, OCURRIO UN ERROR",
    MENSAJE_ERROR_PK: "ERROR, YA EXISTE UN REGISTRO CON ESE ID",
    MENSAJE_ERROR_DUPLICIDAD: "ERROR, YA EXISTE UN REGISTRO CON ESOS DATOS",
    MENSAJE_ERROR_USUARIO_PASSWORD: "ERROR, USUARIO Y/O PASSWORD INCORRECTO(S)",
    MENSAJE_ERROR_TOKEN: "ERROR, TOKEN INCORRECTO",
    MENSAJE_ERROR_VALOR_ESTRUCTURA: "ERROR, VALOR Y/O ESTRUCTURA INCORRECTA",
    MENSAJE_ERROR_VALOR: "ERROR, VALOR INCORRECTO",
    
    
    //******************************TIPO**********************************

    DOM_TIPO_CREDITO: "1",
    DOM_OFICINAS: "2",
    DOM_ESTADO_CREDITO: "3",
    DOM_GENERO: "4",
    DOM_TIPO_MOTIVO_RECHAZO: "5"

}
